title: Tomasz Jantos
email: your-email@example.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll
facebook_profile: ''
instagram_profile: ''

collections:
  categories:
    output: true
    permalink: "/categories/:slug"
  products:
    output: true
    permalink: "/products/:slug"


theme: minima
plugins:
  - jekyll-feed

exclude:
   - vendor # fix for some old bug
   - .jekyll-cache
   - tj*
   - package.json
   - yarn.lock
   - node_modules
   - Makefile
   - Gem*

defaults:
  -
    scope:
      path: ""
      type: "categories"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "default"